version: "3"

services:
    witnesshost:
        container_name: witnesshost
        hostname: witnesshost
        image: gleif/keri:latest
        tty: true
        ports:
            - 5642:5642  # witness
            - 5643:5643  # witness
            - 5644:5644  # witness
        entrypoint: kli witness demo

    dkr:
        container_name: dkr
        hostname: dkr
        build:
            context: .
            dockerfile: ./images/dkr.dockerfile
        image: gleif/dkr:latest
        tty: true
        volumes:
            - ~/VSCode/did-keri-resolver/volume/dkr/examples:/usr/local/var/webs/volume/dkr/examples
            - ~/VSCode/did-keri-resolver/volume/dkr/pages:/usr/local/var/webs/volume/dkr/pages

    did-webs-service:
        container_name: did-webs-service
        hostname: did-webs-service
        build:
            context: .
            dockerfile: ./images/did-webs-service.dockerfile
        # image: ./images/did-webs-service:latest
        ports:
            - 7676:7676
        tty: true
        volumes:
            - ~/VSCode/did-keri-resolver/volume/dkr/examples:/usr/local/var/webs/volume/dkr/examples
            - ~/VSCode/did-keri-resolver/volume/dkr/pages:/usr/local/var/webs/volume/dkr/pages

    did-webs-resolver-service:
        container_name: did-webs-resolver
        hostname: did-webs-resolver
        build:
            context: .
            dockerfile: ./images/did-webs-resolver-service.dockerfile
        # image: gleif/did-webs-resolver:latest
        ports:
            - 7677:7677
        tty: true
